# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the Noise IKpsk2 cryptographic framework
#
obj-$(CONFIG_NOISE_IKPSK2) += noise_ikpsk2.o

noise_ikpsk2-y := noise_main.o noise_crypto.o handshake.o noise_transport.o noise_ulp.o
